name: Caching test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache
        id: cache-result
        uses: actions/cache@v4
        with:
          path: /tmp/cache-result
          key: ${{ runner.os }}-cache

      - name: Debug pwd
        run: pwd

      - name: Debug ls
        run: ls -la

      - name: Generate
        if: steps.cache-result.outputs.cache-hit != 'true'
        run: ./generate.sh

      - name: Use
        run: ./use.sh
