name: Caching test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Primes
        id: cache-result
        uses: actions/cache@v4
        with:
          path: /tmp/cache-result
          key: ${{ runner.os }}-cache

      - name: Generate
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate.sh

      - name: Use
        run: /use.sh
